### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by HUMENTH** [decipher3114/Capter#1]
not compatible with MacOS 11.6.1

<img width="1536" alt="Screenshot 2024-09-09 at 3 01 53 PM" src="https://github.com/user-attachments/assets/a5f2a7b1-9bd4-4e63-a929-72656ebad802">

**Comment by decipher3114** [comment]
I didn't test it on a Mac. Also, it could be a restriction from the packager's code.
I have to check it.

**Comment by decipher3114** [comment]
Fixed in https://github.com/decipher3114/Capter/releases/tag/v1.1.1
