### ISSUE TITLE
Crash on macOS 15.1 (m1 air)

### ISSUE THREAD

**Issue by titoOdUA** [decipher3114/Capter#7]
Works perfectly fine on my linux disto but crashes on macOS 15.1

After installation through releases page it errors out. There is a popup that app is damaged and button to move it to trash.
If I try to cargo run it I get an error while creating a tray_icon. The error points out that winit event loop should be enabled first.
Also I think there is a problem that after crash the file descriptor still there and app can't create a socket because the name is in use, so it can't be launched again.

Maybe I am doing something wrong. But can't figure it out.

Was actually in a process of doing similar app, your app gave me some ideas how to tackle problems. Would actually like to contribute with something if you would like some help, but need to be able to use it on Mac for it =)

**Comment by decipher3114** [comment]
I don't have access to a mac. There is no specific fixes or workarounds applied that macOS requires.

If you can contribute to the project, you are more than welcome.

Soon, the development will be resumed and I'll work to populate the configuration with actually needed features.
