### ISSUE TITLE
[request] Expose API for area selector

### ISSUE THREAD

**Issue by TheBearodactyl** [decipher3114/Capter#9]
i was wondering if you could also add a library part of this app that exposes a few things for people to be able to use the screen area selector ([yk this thing](https://github.com/user-attachments/assets/59318f05-70cd-4971-9a9b-523c009690b9)) to return a `((i32, i32), (i32, i32))` value?

**Comment by decipher3114** [comment]
That is inefficient and not needed as none requires that. Both `iced` and `tiny-skia` requires only the top-left and the size of the selection.

**Comment by TheBearodactyl** [comment]
well then could it return those 2 values in that case?

**Comment by decipher3114** [comment]
Since everything is handled by iced event loop, nothing can be returned from the function. It can only trigger `update` function after selection which can further utilise the value.
